// ComplianceDesk v4.0 - Complete Suite
var CONFIG={GAS_URL:'',APP_NAME:'ComplianceDesk',VERSION:'4.0.0',WORKFLOW_STATES:['PendingData','DataReceived','ValidationFailed','ReadyToFile','Filed','Acknowledged'],WORKFLOW_COLORS:{PendingData:'#f59e0b',DataReceived:'#3b82f6',ValidationFailed:'#ef4444',ReadyToFile:'#8b5cf6',Filed:'#10b981',Acknowledged:'#059669'},WORKFLOW_LABELS:{PendingData:'Pending Data',DataReceived:'Data Received',ValidationFailed:'Validation Failed',ReadyToFile:'Ready to File',Filed:'Filed',Acknowledged:'Acknowledged'},CLIENT_TYPES:['Pvt Ltd','LLP','Proprietorship','Partnership','Trust/Society'],CATEGORIES:['GST','TDS','ROC','Company Law','Director','Income Tax','Audit'],CHANNELS:['WhatsApp','Email','SMS','Phone','In Person'],COMM_TYPES:['Reminder','Follow-up','Acknowledgment','Query','Update','Escalation'],FIRM_NAME:'',FIRM_PHONE:'',STAFF:['Ravi','Meena','Suresh']};
function isConfigured(){return CONFIG.GAS_URL&&CONFIG.GAS_URL.length>10;}
var Validators={PAN:function(p){return /^[A-Z]{5}[0-9]{4}[A-Z]$/.test(String(p||'').toUpperCase());},GSTIN:function(g){if(!g)return true;return /^\d{2}[A-Z]{5}\d{4}[A-Z]\d[Z][A-Z\d]$/.test(String(g).toUpperCase());},CIN:function(c){if(!c)return true;return /^[UL]\d{5}[A-Z]{2}\d{4}[A-Z]{3}\d{6}$/.test(String(c).toUpperCase());},DIN:function(d){if(!d)return true;return /^\d{8}$/.test(String(d));},email:function(e){return /^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(String(e||''));},phone:function(p){if(!p)return true;return /^[6-9]\d{9}$/.test(String(p));}};

var currentPage='dashboard';
function navigateTo(page){currentPage=page;document.querySelectorAll('.nav-item').forEach(function(el){el.classList.toggle('active',el.dataset.page===page);});renderPage(page);}
function renderPage(page){var c=document.getElementById('pageContent');c.innerHTML='<div class="loading-screen"><div class="spinner"></div><p>Loading...</p></div>';try{switch(page){case 'dashboard':renderDashboard(c);break;case 'clients':renderClients(c);break;case 'calendar':renderCalendar(c);break;case 'workflow':renderWorkflow(c);break;case 'validation':renderValidation(c);break;case 'communications':renderCommunications(c);break;case 'reminders':renderReminders(c);break;case 'team':renderTeam(c);break;case 'billing':renderBilling(c);break;case 'portal':renderPortal(c);break;case 'settings':renderSettings(c);break;default:c.innerHTML='<h1>Not found</h1>';}}catch(e){c.innerHTML='<div class="info-box danger"><div class="ib-title">Error</div><div class="ib-text">'+e.message+'</div></div>';console.error(e);}}
function openModal(t,h){document.getElementById('modalTitle').textContent=t;document.getElementById('modalBody').innerHTML=h;document.getElementById('modalOverlay').style.display='flex';}
function closeModal(){document.getElementById('modalOverlay').style.display='none';}
function showToast(m,t){t=t||'info';var c=document.getElementById('toastContainer'),d=document.createElement('div');d.className='toast '+t;d.textContent=m;c.appendChild(d);setTimeout(function(){d.remove();},4000);}
function statusBadge(s){var m={PendingData:'badge-pending',DataReceived:'badge-received',ValidationFailed:'badge-failed',ReadyToFile:'badge-ready',Filed:'badge-filed',Acknowledged:'badge-ack'};return '<span class="badge '+(m[s]||'')+'"><span class="dot"></span>'+(CONFIG.WORKFLOW_LABELS[s]||s)+'</span>';}
function daysLeft(dl){if(!dl)return{days:0,label:'No date',cls:''};var n=new Date();n.setHours(0,0,0,0);var d=new Date(dl),diff=Math.ceil((d-n)/86400000);if(diff<0)return{days:diff,label:Math.abs(diff)+'d overdue',cls:'overdue'};if(diff<=3)return{days:diff,label:diff+'d left',cls:'due-soon'};return{days:diff,label:diff+'d left',cls:''};}
function formatDate(ds){if(!ds)return '-';return new Date(ds).toLocaleDateString('en-IN',{day:'2-digit',month:'short',year:'numeric'});}
function updateConnectionStatus(){var el=document.getElementById('connectionStatus');if(isConfigured())el.innerHTML='<span class="status-dot online"></span><span>Connected to Sheets</span>';else el.innerHTML='<span class="status-dot offline"></span><span>Demo Mode (Local)</span>';}

// WHATSAPP FUNCTIONS
function buildWAMsg(compName,clientName,deadline,firmName){var dl=daysLeft(deadline),urgency=dl.cls==='overdue'?'OVERDUE':'due on '+deadline;var msg='Dear '+clientName+',\n\nReminder: *'+compName+'* is *'+urgency+'*.';if(dl.cls==='overdue')msg+='\n\nThis was due '+deadline+' ('+Math.abs(dl.days)+' days overdue). Please provide documents immediately.';else if(dl.days<=7)msg+='\n\nOnly *'+dl.days+' days left*. Please share pending documents urgently.';msg+='\n\n*Documents needed:*\n';if(compName.indexOf('GST')>=0)msg+='- Sales & purchase invoices\n- Credit/debit notes\n- Bank statements';else if(compName.indexOf('TDS')>=0)msg+='- TDS challans\n- Deductee details with PAN';else if(compName.indexOf('ROC')>=0||compName.indexOf('Form')>=0)msg+='- Board resolution\n- Financial statements';else if(compName.indexOf('Income Tax')>=0)msg+='- Form 16/16A\n- Bank statements\n- Investment proofs';else if(compName.indexOf('DIR')>=0)msg+='- Director PAN & Aadhaar\n- Updated contact info';else msg+='- Relevant documents as discussed';msg+='\n\nPlease reply or call for queries.';if(firmName)msg+='\n\nRegards,\n'+firmName;return msg;}
function openWhatsApp(phone,message){if(!phone){showToast('No phone number','error');return;}var num=String(phone).replace(/[^0-9]/g,'');if(num.length===10)num='91'+num;window.open('https://wa.me/'+num+'?text='+encodeURIComponent(message),'_blank');}
function sendWAReminder(compId){var cs=getComps(),c=cs.find(function(x){return x.ID===compId;});if(!c)return;var cls=getClients(),cl=cls.find(function(x){return x.ID===c.ClientID;});if(!cl||!cl.Phone){showToast('No phone for '+(cl?cl.LegalName:'client'),'error');return;}var firm=_s.get('firmName')||'';openWhatsApp(cl.Phone,buildWAMsg(c.Name,cl.ContactName||cl.LegalName,c.Deadline,firm));apiLogComm({clientId:cl.ID,clientName:cl.LegalName,type:'Reminder',channel:'WhatsApp',message:'WA reminder: '+c.Name+' ('+c.Deadline+')'});showToast('WhatsApp opened for '+cl.LegalName,'success');}
function sendWABulk(ids){if(!ids||!ids.length){showToast('Nothing to send','error');return;}var d=0;ids.forEach(function(id){setTimeout(function(){sendWAReminder(id);},d);d+=1500;});showToast('Opening '+ids.length+' reminders...','info');}
function sendWASummary(clientId){var cls=getClients(),cl=cls.find(function(x){return x.ID===clientId;});if(!cl||!cl.Phone){showToast('No phone','error');return;}var cs=getComps({clientId:clientId}).filter(function(c){return c.Status!=='Filed'&&c.Status!=='Acknowledged';});if(!cs.length){showToast('No pending items','info');return;}var firm=_s.get('firmName')||'';cs.sort(function(a,b){return(a.Deadline||'').localeCompare(b.Deadline||'');});var msg='Dear '+(cl.ContactName||cl.LegalName)+',\n\nPending compliance summary:\n\n';cs.forEach(function(c,i){var dl=daysLeft(c.Deadline),icon=dl.cls==='overdue'?'🔴':dl.cls==='due-soon'?'🟡':'🟢';msg+=(i+1)+'. '+icon+' *'+c.Name+'* — '+c.Deadline+' ('+dl.label+')\n';});msg+='\nPlease share documents at earliest.';if(firm)msg+='\n\nRegards,\n'+firm;openWhatsApp(cl.Phone,msg);apiLogComm({clientId:cl.ID,clientName:cl.LegalName,type:'Reminder',channel:'WhatsApp',message:'Summary sent: '+cs.length+' items'});}

// STORAGE
var _s={get:function(k){try{return JSON.parse(localStorage.getItem('cd_'+k));}catch(e){return null;}},set:function(k,v){localStorage.setItem('cd_'+k,JSON.stringify(v));}};
var MONTH_NAMES=['Jan','Feb','Mar','Apr','May','Jun','Jul','Aug','Sep','Oct','Nov','Dec'];
var COMP_T={'Pvt Ltd':[{n:'GSTR-1',f:'Monthly',d:11,c:'GST'},{n:'GSTR-3B',f:'Monthly',d:20,c:'GST'},{n:'TDS Return (24Q)',f:'Quarterly',d:31,c:'TDS'},{n:'ROC MGT-7',f:'Annually',mo:11,d:30,c:'ROC'},{n:'ROC AOC-4',f:'Annually',mo:10,d:30,c:'ROC'},{n:'Board Meeting',f:'Quarterly',d:30,c:'Company Law'},{n:'DIR-3 KYC',f:'Annually',mo:9,d:30,c:'Director'},{n:'Income Tax Return',f:'Annually',mo:10,d:31,c:'Income Tax'}],LLP:[{n:'GSTR-1',f:'Monthly',d:11,c:'GST'},{n:'GSTR-3B',f:'Monthly',d:20,c:'GST'},{n:'LLP Form 11',f:'Annually',mo:5,d:30,c:'ROC'},{n:'LLP Form 8',f:'Annually',mo:10,d:30,c:'ROC'},{n:'Income Tax Return',f:'Annually',mo:10,d:31,c:'Income Tax'}],Proprietorship:[{n:'GSTR-1',f:'Monthly',d:11,c:'GST'},{n:'GSTR-3B',f:'Monthly',d:20,c:'GST'},{n:'Income Tax Return',f:'Annually',mo:7,d:31,c:'Income Tax'}],Partnership:[{n:'GSTR-1',f:'Monthly',d:11,c:'GST'},{n:'GSTR-3B',f:'Monthly',d:20,c:'GST'},{n:'Income Tax Return',f:'Annually',mo:7,d:31,c:'Income Tax'},{n:'TDS Return',f:'Quarterly',d:31,c:'TDS'}],'Trust/Society':[{n:'GSTR-1',f:'Monthly',d:11,c:'GST'},{n:'GSTR-3B',f:'Monthly',d:20,c:'GST'},{n:'Income Tax Return',f:'Annually',mo:10,d:31,c:'Income Tax'}]};
function genId(){return Math.random().toString(36).substr(2,8);}
function genComps(cid,cn,ct){var ts=COMP_T[ct]||[],comps=_s.get('compliances')||[],now=new Date(),cnt=0,sts=['PendingData','DataReceived','ReadyToFile','Filed','Acknowledged'],asgn=['Ravi','Meena','Suresh'];ts.forEach(function(t){var ps=[];if(t.f==='Monthly'){for(var m=0;m<3;m++){var dl=new Date(now.getFullYear(),now.getMonth()+m+1,t.d);ps.push({dl:dl.toISOString().split('T')[0],p:MONTH_NAMES[(now.getMonth()+m)%12]+' '+now.getFullYear()});}}else if(t.f==='Quarterly'){var cq=Math.floor(now.getMonth()/3);for(var q=0;q<2;q++){var qm=((cq+q)%4)*3+2,yr=now.getFullYear()+(cq+q>=4?1:0);ps.push({dl:new Date(yr,qm,t.d).toISOString().split('T')[0],p:'Q'+((cq+q)%4+1)+' '+yr});}}else{var mn=(t.mo||3)-1,yr2=mn<now.getMonth()?now.getFullYear()+1:now.getFullYear();ps.push({dl:new Date(yr2,mn,t.d).toISOString().split('T')[0],p:'FY '+(yr2-1)+'-'+String(yr2).slice(2)});}ps.forEach(function(p){comps.push({ID:genId(),ClientID:cid,ClientName:cn,Name:t.n,Category:t.c,Frequency:t.f,Deadline:p.dl,Status:sts[Math.floor(Math.random()*sts.length)],AssignedTo:asgn[Math.floor(Math.random()*3)],FilingDate:'',AckNumber:'',Notes:'',Period:p.p,CreatedAt:new Date().toISOString(),UpdatedAt:new Date().toISOString()});cnt++;});});_s.set('compliances',comps);return cnt;}
function initDemo(){_s.set('_init',true);_s.set('clients',[]);_s.set('compliances',[]);_s.set('communications',[]);[{ln:'Sharma Enterprises Pvt Ltd',pan:'ABCDS1234E',gst:'27ABCDS1234E1Z5',cin:'U72200MH2020PTC123456',ty:'Pvt Ltd',cn:'Rajesh Sharma',em:'rajesh@sharmaent.com',ph:'9876543210'},{ln:'Gupta Trading LLP',pan:'AACFG5678H',gst:'07AACFG5678H1ZR',cin:'',ty:'LLP',cn:'Amit Gupta',em:'amit@guptatrading.in',ph:'9812345678'},{ln:'Priya Fashions',pan:'BKMPF9012L',gst:'29BKMPF9012L1ZQ',cin:'',ty:'Proprietorship',cn:'Priya Reddy',em:'priya@priyafashions.com',ph:'9988776655'}].forEach(function(d){apiCreateClient({legalName:d.ln,pan:d.pan,gstin:d.gst,cin:d.cin,clientType:d.ty,contactName:d.cn,email:d.em,phone:d.ph});});}
function ensureInit(){if(!_s.get('_init'))initDemo();}
function apiCreateClient(d){var cls=_s.get('clients')||[],errs=[];if(!d.legalName)errs.push('Name required');if(!d.pan||!Validators.PAN(d.pan))errs.push('Invalid PAN');if(d.gstin&&!Validators.GSTIN(d.gstin))errs.push('Invalid GSTIN');if(d.gstin&&cls.some(function(c){return c.GSTIN===d.gstin.toUpperCase();}))errs.push('Duplicate GSTIN');if(d.pan&&cls.some(function(c){return c.PAN===d.pan.toUpperCase();}))errs.push('Duplicate PAN');if(!d.email||!Validators.email(d.email))errs.push('Invalid email');if(errs.length)return{success:false,errors:errs};var id=genId();cls.push({ID:id,LegalName:d.legalName,PAN:d.pan.toUpperCase(),GSTIN:d.gstin?d.gstin.toUpperCase():'',CIN:d.cin?d.cin.toUpperCase():'',ClientType:d.clientType,ContactName:d.contactName||'',Email:d.email,Phone:d.phone||'',Status:'Active',CreatedAt:new Date().toISOString(),UpdatedAt:new Date().toISOString()});_s.set('clients',cls);var cc=genComps(id,d.legalName,d.clientType);return{success:true,clientId:id,message:'Client created. '+cc+' compliances generated.',compliancesGenerated:cc};}
function apiUpdateClient(id,d){var cls=_s.get('clients')||[],idx=-1;for(var i=0;i<cls.length;i++)if(cls[i].ID===id){idx=i;break;}if(idx===-1)return{success:false,errors:['Not found']};if(d.legalName)cls[idx].LegalName=d.legalName;if(d.pan)cls[idx].PAN=d.pan.toUpperCase();if(d.gstin!==undefined)cls[idx].GSTIN=(d.gstin||'').toUpperCase();if(d.cin!==undefined)cls[idx].CIN=(d.cin||'').toUpperCase();if(d.clientType)cls[idx].ClientType=d.clientType;if(d.contactName!==undefined)cls[idx].ContactName=d.contactName;if(d.email)cls[idx].Email=d.email;if(d.phone!==undefined)cls[idx].Phone=d.phone;cls[idx].UpdatedAt=new Date().toISOString();_s.set('clients',cls);return{success:true};}
function apiUpdateComp(id,d){var cs=_s.get('compliances')||[],idx=-1;for(var i=0;i<cs.length;i++)if(cs[i].ID===id){idx=i;break;}if(idx===-1)return{success:false,errors:['Not found']};if(d.status){var ci=CONFIG.WORKFLOW_STATES.indexOf(cs[idx].Status),ni=CONFIG.WORKFLOW_STATES.indexOf(d.status);if(ni>ci+1)return{success:false,errors:['Cannot skip stages']};if(d.status==='Filed'&&!d.filingDate&&!cs[idx].FilingDate)return{success:false,errors:['Filing date required']};cs[idx].Status=d.status;}if(d.assignedTo!==undefined)cs[idx].AssignedTo=d.assignedTo;if(d.filingDate)cs[idx].FilingDate=d.filingDate;if(d.ackNumber)cs[idx].AckNumber=d.ackNumber;if(d.notes!==undefined)cs[idx].Notes=d.notes;cs[idx].UpdatedAt=new Date().toISOString();_s.set('compliances',cs);return{success:true};}
function apiLogComm(d){var cs=_s.get('communications')||[];cs.push({ID:genId(),ClientID:d.clientId,ClientName:d.clientName||'',Type:d.type||'Note',Channel:d.channel||'Manual',Message:d.message,SentAt:new Date().toISOString(),SentBy:'You'});_s.set('communications',cs);return{success:true};}
function getClients(){ensureInit();return _s.get('clients')||[];}
function getComps(f){ensureInit();var c=_s.get('compliances')||[];if(f&&f.clientId)c=c.filter(function(x){return x.ClientID===f.clientId;});return c;}
function getComms(cid){ensureInit();var c=_s.get('communications')||[];if(cid)c=c.filter(function(x){return x.ClientID===cid;});return c.reverse();}

// DASHBOARD DATA
function getDash(){ensureInit();var cls=getClients(),cs=getComps(),td=new Date().toISOString().split('T')[0],n7=new Date(Date.now()+7*86400000).toISOString().split('T')[0];return{stats:{total:cs.length,filed:cs.filter(function(c){return c.Status==='Filed'||c.Status==='Acknowledged';}).length,overdue:cs.filter(function(c){return c.Deadline<td&&c.Status!=='Filed'&&c.Status!=='Acknowledged';}).length,pendingData:cs.filter(function(c){return c.Status==='PendingData';}).length,dueThisWeek:cs.filter(function(c){return c.Deadline>=td&&c.Deadline<=n7&&c.Status!=='Filed'&&c.Status!=='Acknowledged';}).length,clientCount:cls.length},categories:(function(){var cats={};cs.forEach(function(c){if(!cats[c.Category])cats[c.Category]={total:0,filed:0,overdue:0};cats[c.Category].total++;if(c.Status==='Filed'||c.Status==='Acknowledged')cats[c.Category].filed++;if(c.Deadline<td&&c.Status!=='Filed'&&c.Status!=='Acknowledged')cats[c.Category].overdue++;});return cats;})(),clientSummary:cls.map(function(cl){var cc=cs.filter(function(c){return c.ClientID===cl.ID;});return{id:cl.ID,name:cl.LegalName,type:cl.ClientType,phone:cl.Phone,total:cc.length,filed:cc.filter(function(c){return c.Status==='Filed'||c.Status==='Acknowledged';}).length,overdue:cc.filter(function(c){return c.Deadline<td&&c.Status!=='Filed'&&c.Status!=='Acknowledged';}).length,pending:cc.filter(function(c){return c.Status==='PendingData';}).length};}),upcoming:cs.filter(function(c){return c.Status!=='Filed'&&c.Status!=='Acknowledged';}).sort(function(a,b){return(a.Deadline||'').localeCompare(b.Deadline||'');}).slice(0,10)};}

// DASHBOARD
function renderDashboard(el){var d=getDash(),s=d.stats,today=new Date().toLocaleDateString('en-IN',{weekday:'long',year:'numeric',month:'long',day:'numeric'});var h='<div class="page-header"><div><h1>Dashboard</h1><div class="subtitle">'+today+'</div></div></div><div class="stat-grid"><div class="stat-card" style="background:#eff6ff"><div class="stat-value" style="color:#3b82f6">'+s.total+'</div><div class="stat-label" style="color:#3b82f6">Total Compliances</div></div><div class="stat-card" style="background:#fef2f2"><div class="stat-value" style="color:#ef4444">'+s.overdue+'</div><div class="stat-label" style="color:#ef4444">Overdue</div></div><div class="stat-card" style="background:#fffbeb"><div class="stat-value" style="color:#f59e0b">'+s.dueThisWeek+'</div><div class="stat-label" style="color:#f59e0b">Due This Week</div></div><div class="stat-card" style="background:#ecfdf5"><div class="stat-value" style="color:#10b981">'+s.filed+'</div><div class="stat-label" style="color:#10b981">Filed</div></div><div class="stat-card" style="background:#f5f3ff"><div class="stat-value" style="color:#8b5cf6">'+s.pendingData+'</div><div class="stat-label" style="color:#8b5cf6">Pending Data</div></div><div class="stat-card" style="background:#ecfeff"><div class="stat-value" style="color:#06b6d4">'+s.clientCount+'</div><div class="stat-label" style="color:#06b6d4">Active Clients</div></div></div>';
h+='<div style="display:grid;grid-template-columns:1fr 1fr;gap:20px"><div class="card"><div class="card-title">Upcoming Deadlines</div>';d.upcoming.forEach(function(c){var dl=daysLeft(c.Deadline),col=dl.cls==='overdue'?'#ef4444':dl.cls==='due-soon'?'#f59e0b':'#6b7280';h+='<div class="deadline-item '+dl.cls+'"><div style="flex:1"><div style="font-size:13px;font-weight:600">'+c.Name+'</div><div style="font-size:11px;color:#6b7280">'+c.ClientName+'</div></div><div style="text-align:right;margin-right:10px"><div style="font-size:12px;font-weight:700;color:'+col+'">'+dl.label+'</div><div style="font-size:11px;color:#9ca3af">'+c.Deadline+'</div></div><button class="wa-btn-sm" onclick="event.stopPropagation();sendWAReminder(\''+c.ID+'\')" title="Send WhatsApp Reminder">💬</button></div>';});if(!d.upcoming.length)h+='<p style="color:#9ca3af;font-size:13px">All caught up!</p>';h+='</div>';
h+='<div class="card"><div class="card-title">Category Completion</div>';Object.keys(d.categories).forEach(function(nm){var x=d.categories[nm],pct=x.total?Math.round(x.filed/x.total*100):0;h+='<div style="margin-bottom:12px"><div style="display:flex;justify-content:space-between;margin-bottom:6px"><span style="font-size:13px;font-weight:600">'+nm+'</span><span style="font-size:12px;color:#6b7280">'+x.filed+'/'+x.total+(x.overdue>0?' <span style="color:#ef4444">('+x.overdue+' overdue)</span>':'')+'</span></div><div class="progress-bar"><div class="progress-fill" style="width:'+pct+'%;background:'+(x.overdue>0?'linear-gradient(90deg,#10b981,#f59e0b)':'#10b981')+'"></div></div></div>';});h+='</div></div>';
h+='<div class="card" style="margin-top:16px"><div style="display:flex;justify-content:space-between;align-items:center;margin-bottom:16px"><div class="card-title" style="margin-bottom:0">Client Summary</div></div><div class="table-container" style="border:none"><table class="data-table"><thead><tr><th>Client</th><th>Type</th><th>Total</th><th>Filed</th><th>Pending</th><th>Overdue</th><th>%</th><th>Action</th></tr></thead><tbody>';d.clientSummary.forEach(function(c){var pct=c.total?Math.round(c.filed/c.total*100):0,col=pct>=70?'#10b981':pct>=40?'#f59e0b':'#ef4444';h+='<tr><td style="font-weight:600">'+c.name+'</td><td><span class="tag">'+c.type+'</span></td><td style="font-weight:600">'+c.total+'</td><td style="color:#10b981;font-weight:600">'+c.filed+'</td><td style="color:#f59e0b;font-weight:600">'+c.pending+'</td><td style="color:#ef4444;font-weight:600">'+c.overdue+'</td><td><div style="display:flex;align-items:center;gap:8px"><div class="progress-bar" style="flex:1"><div class="progress-fill" style="width:'+pct+'%;background:'+col+'"></div></div><span style="font-size:12px;font-weight:700">'+pct+'%</span></div></td><td style="white-space:nowrap">'+(c.phone?'<button class="wa-btn-sm" onclick="event.stopPropagation();sendWASummary(\''+c.id+'\')" title="WhatsApp summary" style="margin-right:4px">📱</button>':'')+'<button class="wa-btn-sm" onclick="event.stopPropagation();generateClientReport(\''+c.id+'\')" title="PDF Report" style="background:#8b5cf615">📄</button></td></tr>';});h+='</tbody></table></div></div>';el.innerHTML=h;}

// CLIENTS
function renderClients(el){var cls=getClients(),cs=getComps();window._cls=cls;window._cs=cs;el.innerHTML='<div class="page-header"><div><h1>Clients</h1><div class="subtitle">'+cls.length+' registered</div></div><button class="btn btn-primary" onclick="showClientForm()">+ Add Client</button></div><div class="search-box"><svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><circle cx="11" cy="11" r="8"/><line x1="21" y1="21" x2="16.65" y2="16.65"/></svg><input class="form-input" id="cSearch" placeholder="Search..." oninput="filterCl()"></div><div id="cList"></div>';filterCl();}
function filterCl(){var t=(document.getElementById('cSearch')?document.getElementById('cSearch').value:'').toLowerCase(),cls=window._cls||[],cs=window._cs||[],td=new Date().toISOString().split('T')[0],h='';cls.filter(function(c){return[c.LegalName,c.PAN,c.GSTIN,c.ClientType].some(function(f){return(f||'').toLowerCase().indexOf(t)>=0;});}).forEach(function(cl){var cc=cs.filter(function(c){return c.ClientID===cl.ID;}),ov=cc.filter(function(c){return c.Deadline<td&&c.Status!=='Filed'&&c.Status!=='Acknowledged';}).length,pend=cc.filter(function(c){return c.Status!=='Filed'&&c.Status!=='Acknowledged';}).length;h+='<div class="client-row"><div style="flex:1;cursor:pointer" onclick="showClientForm(\''+cl.ID+'\')"><div style="display:flex;align-items:center;gap:10px;margin-bottom:4px"><span style="font-size:15px;font-weight:700">'+cl.LegalName+'</span><span class="tag">'+cl.ClientType+'</span></div><div style="display:flex;gap:20px;font-size:12px;color:#6b7280"><span>PAN: '+cl.PAN+'</span>'+(cl.GSTIN?'<span>GSTIN: '+cl.GSTIN+'</span>':'')+(cl.Phone?'<span>📞 '+cl.Phone+'</span>':'')+'</div></div><div style="display:flex;align-items:center;gap:10px"><div style="text-align:right"><div style="font-size:13px;font-weight:600">'+cc.length+' compliances</div>'+(ov>0?'<div style="font-size:12px;font-weight:600;color:#ef4444">'+ov+' overdue</div>':'')+'</div>'+(cl.Phone&&pend>0?'<button class="wa-btn" onclick="event.stopPropagation();sendWASummary(\''+cl.ID+'\')" title="Send WhatsApp summary">📱</button>':'')+'</div></div>';});document.getElementById('cList').innerHTML=h||'<p style="text-align:center;padding:40px;color:#9ca3af">No clients found</p>';}
function showClientForm(eid){var cls=window._cls||getClients(),cl=eid?cls.find(function(c){return c.ID===eid;}):null,to=CONFIG.CLIENT_TYPES.map(function(t){return'<option value="'+t+'"'+(cl&&cl.ClientType===t?' selected':'')+'>'+t+'</option>';}).join('');openModal(cl?'Edit Client':'Add Client','<div class="form-row"><div class="form-full form-group"><label class="form-label">Legal Name <span class="required">*</span></label><input class="form-input" id="cf_ln" value="'+(cl?cl.LegalName:'')+'"><div class="form-error" id="e_ln"></div></div></div><div class="form-row"><div class="form-group"><label class="form-label">Type <span class="required">*</span></label><select class="form-input" id="cf_ty">'+to+'</select></div><div class="form-group"><label class="form-label">PAN <span class="required">*</span></label><input class="form-input" id="cf_pan" value="'+(cl?cl.PAN:'')+'" maxlength="10" oninput="this.value=this.value.toUpperCase()"><div class="form-error" id="e_pan"></div></div></div><div class="form-row"><div class="form-group"><label class="form-label">GSTIN</label><input class="form-input" id="cf_gst" value="'+(cl?cl.GSTIN:'')+'" maxlength="15" oninput="this.value=this.value.toUpperCase()"><div class="form-error" id="e_gst"></div></div><div class="form-group"><label class="form-label">CIN</label><input class="form-input" id="cf_cin" value="'+(cl?cl.CIN||'':'')+'" maxlength="21" oninput="this.value=this.value.toUpperCase()"></div></div><div class="form-row"><div class="form-group"><label class="form-label">Contact</label><input class="form-input" id="cf_cn" value="'+(cl?cl.ContactName:'')+'"></div><div class="form-group"><label class="form-label">Email <span class="required">*</span></label><input class="form-input" id="cf_em" value="'+(cl?cl.Email:'')+'"><div class="form-error" id="e_em"></div></div></div><div class="form-row"><div class="form-group"><label class="form-label">Phone (for WhatsApp) <span class="required">*</span></label><input class="form-input" id="cf_ph" value="'+(cl?cl.Phone:'')+'" maxlength="10" placeholder="9876543210"><div class="form-error" id="e_ph"></div><div class="form-hint">10-digit mobile number for WhatsApp reminders</div></div></div><div class="modal-footer"><button class="btn btn-secondary" onclick="closeModal()">Cancel</button><button class="btn btn-primary" onclick="submitCl(\''+(eid||'')+'\')">'+(cl?'Update':'Add Client')+'</button></div>');}
function submitCl(eid){['ln','pan','gst','em','ph'].forEach(function(f){var e=document.getElementById('e_'+f);if(e)e.textContent='';});var d={legalName:document.getElementById('cf_ln').value.trim(),clientType:document.getElementById('cf_ty').value,pan:document.getElementById('cf_pan').value.trim(),gstin:document.getElementById('cf_gst').value.trim(),cin:document.getElementById('cf_cin').value.trim(),contactName:document.getElementById('cf_cn').value.trim(),email:document.getElementById('cf_em').value.trim(),phone:document.getElementById('cf_ph').value.trim()},err=false;function se(f,m){var e=document.getElementById('e_'+f);if(e)e.textContent=m;err=true;}if(!d.legalName)se('ln','Required');if(!d.pan)se('pan','Required');else if(!Validators.PAN(d.pan))se('pan','Invalid');if(d.gstin&&!Validators.GSTIN(d.gstin))se('gst','Invalid');if(!d.email)se('em','Required');else if(!Validators.email(d.email))se('em','Invalid');if(d.phone&&!Validators.phone(d.phone))se('ph','Invalid 10-digit number');if(err)return;var r=eid?apiUpdateClient(eid,d):apiCreateClient(d);if(r.success){closeModal();showToast(r.message||(eid?'Updated':'Created'),'success');renderClients(document.getElementById('pageContent'));}else(r.errors||[]).forEach(function(e){showToast(e,'error');});}

// CALENDAR
var _calF='all',_calC='all';
function renderCalendar(el){window._calCs=getComps();_calF='all';_calC='all';var cats=[];window._calCs.forEach(function(c){if(cats.indexOf(c.Category)<0)cats.push(c.Category);});el.innerHTML='<div class="page-header"><div><h1>Compliance Calendar</h1><div class="subtitle">'+window._calCs.length+' items</div></div></div><div class="filter-bar"><button class="filter-btn active" data-filter="all" onclick="setCalF(\'all\')">All</button><button class="filter-btn" data-filter="overdue" onclick="setCalF(\'overdue\')">Overdue</button><button class="filter-btn" data-filter="week" onclick="setCalF(\'week\')">Due This Week</button><button class="filter-btn" data-filter="pending" onclick="setCalF(\'pending\')">Pending</button><button class="filter-btn" data-filter="filed" onclick="setCalF(\'filed\')">Filed</button><select class="form-input" style="width:auto;padding:8px 12px;font-size:13px" onchange="setCalC(this.value)"><option value="all">All Categories</option>'+cats.map(function(c){return'<option value="'+c+'">'+c+'</option>';}).join('')+'</select></div><div class="table-container" id="calTbl"></div>';renderCalTbl();}
function setCalF(f){_calF=f;document.querySelectorAll('.filter-btn').forEach(function(e){e.classList.toggle('active',e.dataset.filter===f);});renderCalTbl();}
function setCalC(c){_calC=c;renderCalTbl();}
function renderCalTbl(){var all=window._calCs||[],td=new Date().toISOString().split('T')[0],n7=new Date(Date.now()+7*86400000).toISOString().split('T')[0],f=all;if(_calF==='overdue')f=f.filter(function(c){return c.Deadline<td&&c.Status!=='Filed'&&c.Status!=='Acknowledged';});if(_calF==='week')f=f.filter(function(c){return c.Deadline>=td&&c.Deadline<=n7&&c.Status!=='Filed'&&c.Status!=='Acknowledged';});if(_calF==='pending')f=f.filter(function(c){return c.Status==='PendingData';});if(_calF==='filed')f=f.filter(function(c){return c.Status==='Filed'||c.Status==='Acknowledged';});if(_calC!=='all')f=f.filter(function(c){return c.Category===_calC;});f.sort(function(a,b){return(a.Deadline||'').localeCompare(b.Deadline||'');});var h='<table class="data-table"><thead><tr><th>Client</th><th>Compliance</th><th>Category</th><th>Period</th><th>Deadline</th><th>Status</th><th>Assigned</th><th>WhatsApp</th></tr></thead><tbody>';f.forEach(function(c){var dl=daysLeft(c.Deadline),ov=dl.cls==='overdue'&&c.Status!=='Filed'&&c.Status!=='Acknowledged',dc=ov?'#ef4444':dl.cls==='due-soon'?'#f59e0b':'#374151',showWA=c.Status!=='Filed'&&c.Status!=='Acknowledged';h+='<tr style="background:'+(ov?'#fef2f2':'transparent')+'"><td style="font-weight:600;cursor:pointer" onclick="showCompDtl(\''+c.ID+'\')">'+c.ClientName+'</td><td>'+c.Name+'</td><td><span class="badge-sm" style="background:#f3f4f6">'+c.Category+'</span></td><td style="color:#6b7280">'+(c.Period||'')+'</td><td><span style="font-weight:600;color:'+dc+'">'+c.Deadline+'</span></td><td>'+statusBadge(c.Status)+'</td><td style="color:#6b7280">'+(c.AssignedTo||'-')+'</td><td>'+(showWA?'<button class="wa-btn-sm" onclick="sendWAReminder(\''+c.ID+'\')" title="Send WhatsApp">💬</button>':'-')+'</td></tr>';});h+='</tbody></table>';if(!f.length)h+='<p style="text-align:center;padding:40px;color:#9ca3af">No items</p>';document.getElementById('calTbl').innerHTML=h;}
function showCompDtl(id){var c=(window._calCs||getComps()).find(function(x){return x.ID===id;});if(!c)return;var sb=CONFIG.WORKFLOW_STATES.map(function(st,i){var ci=CONFIG.WORKFLOW_STATES.indexOf(c.Status),cur=st===c.Status,past=i<ci,col=CONFIG.WORKFLOW_COLORS[st];return'<button onclick="advComp(\''+id+'\',\''+st+'\')" style="flex:1;padding:8px 4px;border-radius:8px;font-size:10px;font-weight:700;cursor:pointer;background:'+(cur?col:past?col+'30':'#f3f4f6')+';color:'+(cur?'#fff':past?col:'#9ca3af')+';border:2px solid '+(cur?col:'transparent')+';font-family:inherit">'+CONFIG.WORKFLOW_LABELS[st]+'</button>';}).join('');openModal('Compliance Detail','<div class="form-row" style="margin-bottom:16px"><div><span style="font-size:11px;color:#6b7280;font-weight:600">CLIENT</span><div style="font-weight:700">'+c.ClientName+'</div></div><div><span style="font-size:11px;color:#6b7280;font-weight:600">COMPLIANCE</span><div style="font-weight:700">'+c.Name+'</div></div><div><span style="font-size:11px;color:#6b7280;font-weight:600">DEADLINE</span><div style="font-weight:600">'+c.Deadline+'</div></div><div><span style="font-size:11px;color:#6b7280;font-weight:600">STATUS</span><div>'+statusBadge(c.Status)+'</div></div></div><div style="margin-bottom:20px"><span style="font-size:12px;color:#6b7280;font-weight:600;display:block;margin-bottom:8px">WORKFLOW</span><div style="display:flex;gap:4px">'+sb+'</div></div><div class="form-row"><div class="form-group"><label class="form-label">Assigned To</label><input class="form-input" id="cd_at" value="'+(c.AssignedTo||'')+'"></div><div class="form-group"><label class="form-label">Filing Date</label><input class="form-input" type="date" id="cd_fd" value="'+(c.FilingDate||'')+'"></div></div><div class="form-row"><div class="form-group"><label class="form-label">Ack Number</label><input class="form-input" id="cd_ack" value="'+(c.AckNumber||'')+'"></div></div><div class="form-group"><label class="form-label">Notes</label><textarea class="form-input" id="cd_notes">'+(c.Notes||'')+'</textarea></div><div class="modal-footer"><button class="btn btn-accent" onclick="sendWAReminder(\''+id+'\')">📱 WhatsApp Reminder</button><button class="btn btn-secondary" onclick="closeModal()">Close</button><button class="btn btn-primary" onclick="saveCompDtl(\''+id+'\')">Save</button></div>'+renderDocChecklist(id,c.Name));}
function advComp(id,st){var fd=document.getElementById('cd_fd')?document.getElementById('cd_fd').value:'';var r=apiUpdateComp(id,{status:st,filingDate:fd});if(r.success){showToast('Updated','success');closeModal();window._calCs=getComps();renderCalTbl();}else showToast((r.errors||['Error']).join(', '),'error');}
function saveCompDtl(id){var r=apiUpdateComp(id,{assignedTo:document.getElementById('cd_at').value,filingDate:document.getElementById('cd_fd').value,ackNumber:document.getElementById('cd_ack').value,notes:document.getElementById('cd_notes').value});if(r.success){showToast('Saved','success');closeModal();window._calCs=getComps();renderCalTbl();}else showToast((r.errors||['Error']).join(', '),'error');}

// WORKFLOW
function renderWorkflow(el){var cs=getComps(),act=cs.filter(function(c){return c.Status!=='Filed'&&c.Status!=='Acknowledged';}),cols=CONFIG.WORKFLOW_STATES.filter(function(s){return s!=='Filed'&&s!=='Acknowledged';});var h='<div class="page-header"><div><h1>Workflow Board</h1><div class="subtitle">'+act.length+' active</div></div><button class="btn btn-secondary btn-sm" onclick="renderWorkflow(document.getElementById(\'pageContent\'))">Refresh</button></div><div class="workflow-board">';cols.forEach(function(st){var items=act.filter(function(c){return c.Status===st;}),col=CONFIG.WORKFLOW_COLORS[st];h+='<div class="workflow-column" style="background:'+col+'08;border-color:'+col+'20"><div class="workflow-column-header"><span class="col-dot" style="background:'+col+'"></span><span class="col-title">'+CONFIG.WORKFLOW_LABELS[st]+'</span><span class="col-count" style="background:'+col+'20;color:'+col+'">'+items.length+'</span></div>';items.forEach(function(c){var dl=daysLeft(c.Deadline),nxt=CONFIG.WORKFLOW_STATES[CONFIG.WORKFLOW_STATES.indexOf(st)+1],dc=dl.cls==='overdue'?'#ef4444':dl.cls==='due-soon'?'#f59e0b':'#6b7280',bg=dl.cls==='overdue'?'#fef2f2':dl.cls==='due-soon'?'#fffbeb':'#f3f4f6';h+='<div class="workflow-card"><div style="display:flex;justify-content:space-between;align-items:start"><div class="wc-name">'+c.Name+'</div><button class="wa-btn-xs" onclick="sendWAReminder(\''+c.ID+'\')" title="WhatsApp">💬</button></div><div class="wc-client">'+c.ClientName+'</div><div class="wc-footer"><span class="wc-days" style="background:'+bg+';color:'+dc+'">'+dl.label+'</span>'+(c.AssignedTo?'<span style="font-size:10px;color:#9ca3af">'+c.AssignedTo+'</span>':'')+'</div>';if(nxt&&nxt!=='Filed'&&nxt!=='Acknowledged')h+='<button class="wc-advance-btn" style="background:'+col+'15;color:'+col+'" onclick="advWf(\''+c.ID+'\',\''+nxt+'\')">Advance &rarr;</button>';h+='</div>';});if(!items.length)h+='<p style="text-align:center;font-size:11px;color:#9ca3af;padding:20px">Empty</p>';h+='</div>';});h+='</div>';el.innerHTML=h;}
function advWf(id,st){var r=apiUpdateComp(id,{status:st});if(r.success){showToast('Moved','success');renderWorkflow(document.getElementById('pageContent'));}else showToast((r.errors||['Error']).join(', '),'error');}

// VALIDATION
var _invs=[];
function renderValidation(el){_invs=[];el.innerHTML='<div class="page-header"><div><h1>Data Validation</h1><div class="subtitle">Validate Indian identifiers</div></div></div><div class="validation-grid"><div class="validation-card"><div class="vc-title">PAN</div><input class="form-input" id="v_pan" placeholder="ABCDE1234F" oninput="this.value=this.value.toUpperCase();vf(\'pan\')"><div class="validation-result neutral" id="vr_pan">5 letters + 4 digits + 1 letter</div></div><div class="validation-card"><div class="vc-title">GSTIN</div><input class="form-input" id="v_gstin" placeholder="27ABCDE1234F1Z5" oninput="this.value=this.value.toUpperCase();vf(\'gstin\')"><div class="validation-result neutral" id="vr_gstin">15 char alphanumeric</div></div><div class="validation-card"><div class="vc-title">CIN</div><input class="form-input" id="v_cin" placeholder="U72200MH2020PTC123456" oninput="this.value=this.value.toUpperCase();vf(\'cin\')"><div class="validation-result neutral" id="vr_cin">21 char company ID</div></div><div class="validation-card"><div class="vc-title">DIN</div><input class="form-input" id="v_din" placeholder="12345678" oninput="vf(\'din\')"><div class="validation-result neutral" id="vr_din">8 digit director ID</div></div></div><div class="card"><div class="card-title">Invoice Duplicate Checker</div><div style="display:flex;gap:8px;margin-bottom:14px"><input class="form-input" id="invIn" placeholder="Invoice number..." onkeydown="if(event.key===\'Enter\')chkInv()" style="flex:1"><button class="btn btn-primary" onclick="chkInv()">Check</button><button class="btn btn-secondary" onclick="_invs=[];document.getElementById(\'invR\').innerHTML=\'\'">Clear</button></div><div id="invR"></div></div>';}
function vf(f){var v=document.getElementById('v_'+f).value.trim(),el=document.getElementById('vr_'+f),hints={pan:'5 letters + 4 digits + 1 letter',gstin:'15 char alphanumeric',cin:'21 char company ID',din:'8 digit director ID'},map={pan:'PAN',gstin:'GSTIN',cin:'CIN',din:'DIN'};if(!v){el.className='validation-result neutral';el.textContent=hints[f];return;}var ok=Validators[map[f]](v);el.className='validation-result '+(ok?'valid':'invalid');el.textContent=ok?'Valid':'Invalid. Expected: '+hints[f];}
function chkInv(){var inp=document.getElementById('invIn'),n=inp.value.trim();if(!n)return;if(_invs.find(function(i){return i.n===n;}))showToast('Duplicate: '+n,'warning');else _invs.push({n:n});inp.value='';inp.focus();var h='';_invs.forEach(function(i){h+='<span style="display:inline-block;padding:4px 12px;border-radius:8px;font-size:12px;font-weight:600;margin:2px;background:#ecfdf5;color:#059669;border:1px solid #bbf7d0">'+i.n+' ✓</span>';});document.getElementById('invR').innerHTML=h;}

// COMMUNICATIONS
function renderCommunications(el){var comms=getComms(),cls=getClients();window._commCls=cls;var chC={WhatsApp:'#25d366',Email:'#3b82f6',SMS:'#8b5cf6',Phone:'#f59e0b','In Person':'#6b7280'},h='<div class="page-header"><div><h1>Communications</h1></div><button class="btn btn-primary" onclick="showCommForm()">+ Log</button></div>';comms.forEach(function(l){var cc=chC[l.Channel]||'#6b7280',tc=l.Type==='Reminder'?'#ef4444':l.Type==='Follow-up'?'#f59e0b':'#059669',tb=l.Type==='Reminder'?'#fef2f2':l.Type==='Follow-up'?'#fffbeb':'#ecfdf5';h+='<div class="comm-item"><div class="comm-icon" style="background:'+cc+'15;color:'+cc+'">'+(l.Channel==='WhatsApp'?'📱':'📧')+'</div><div style="flex:1"><div style="display:flex;justify-content:space-between;margin-bottom:4px"><span style="font-weight:700">'+l.ClientName+'</span><span style="font-size:12px;color:#9ca3af">'+formatDate(l.SentAt)+'</span></div><div style="display:flex;gap:8px;margin-bottom:6px"><span class="badge-sm" style="background:'+tb+';color:'+tc+'">'+l.Type+'</span><span class="badge-sm" style="background:'+cc+'15;color:'+cc+'">'+l.Channel+'</span></div><p style="font-size:13px;color:#4b5563;margin:0">'+l.Message+'</p></div></div>';});if(!comms.length)h+='<p style="text-align:center;padding:40px;color:#9ca3af">No communications yet</p>';el.innerHTML=h;}
function showCommForm(){var cls=window._commCls||getClients(),co=cls.map(function(c){return'<option value="'+c.ID+'" data-name="'+c.LegalName+'">'+c.LegalName+'</option>';}).join(''),to=CONFIG.COMM_TYPES.map(function(t){return'<option>'+t+'</option>';}).join(''),cho=CONFIG.CHANNELS.map(function(c){return'<option>'+c+'</option>';}).join('');openModal('Log Communication','<div class="form-group"><label class="form-label">Client <span class="required">*</span></label><select class="form-input" id="cm_cl"><option value="">Select</option>'+co+'</select></div><div class="form-row"><div class="form-group"><label class="form-label">Type</label><select class="form-input" id="cm_ty">'+to+'</select></div><div class="form-group"><label class="form-label">Channel</label><select class="form-input" id="cm_ch">'+cho+'</select></div></div><div class="form-group"><label class="form-label">Message <span class="required">*</span></label><textarea class="form-input" id="cm_msg"></textarea></div><div class="modal-footer"><button class="btn btn-secondary" onclick="closeModal()">Cancel</button><button class="btn btn-primary" onclick="submitComm()">Log</button></div>');}
function submitComm(){var sel=document.getElementById('cm_cl'),msg=document.getElementById('cm_msg').value.trim();if(!sel.value||!msg){showToast('Client and message required','error');return;}apiLogComm({clientId:sel.value,clientName:sel.options[sel.selectedIndex].dataset.name||'',type:document.getElementById('cm_ty').value,channel:document.getElementById('cm_ch').value,message:msg});closeModal();showToast('Logged','success');renderCommunications(document.getElementById('pageContent'));}

// REMINDERS HUB
function renderReminders(el){var cs=getComps(),cls=getClients(),td=new Date().toISOString().split('T')[0],n7=new Date(Date.now()+7*86400000).toISOString().split('T')[0],n30=new Date(Date.now()+30*86400000).toISOString().split('T')[0];var overdue=cs.filter(function(c){return c.Deadline<td&&c.Status!=='Filed'&&c.Status!=='Acknowledged';}).sort(function(a,b){return(a.Deadline||'').localeCompare(b.Deadline||'');});var dueWeek=cs.filter(function(c){return c.Deadline>=td&&c.Deadline<=n7&&c.Status!=='Filed'&&c.Status!=='Acknowledged';}).sort(function(a,b){return(a.Deadline||'').localeCompare(b.Deadline||'');});var dueMon=cs.filter(function(c){return c.Deadline>n7&&c.Deadline<=n30&&c.Status!=='Filed'&&c.Status!=='Acknowledged';}).sort(function(a,b){return(a.Deadline||'').localeCompare(b.Deadline||'');});
var fn=_s.get('firmName')||'';
var h='<div class="page-header"><div><h1>Reminder Center</h1><div class="subtitle">Send WhatsApp reminders to clients</div></div></div>';
h+='<div class="card" style="margin-bottom:20px"><div style="display:flex;align-items:center;gap:12px;flex-wrap:wrap"><label style="font-size:13px;font-weight:600;white-space:nowrap">Your Firm Name:</label><input class="form-input" id="rem_firm" value="'+fn+'" placeholder="e.g., Sharma & Associates" style="max-width:300px" onchange="_s.set(\'firmName\',this.value);showToast(\'Saved\',\'success\')"><span class="form-hint" style="margin:0">Appears in messages</span></div></div>';
function remSection(title,icon,color,items){h+='<div class="card" style="border-left:4px solid '+color+'"><div style="display:flex;justify-content:space-between;align-items:center;margin-bottom:16px"><div class="card-title" style="margin-bottom:0;color:'+color+'">'+icon+' '+title+' ('+items.length+')</div>';if(items.length>0){var ids=items.map(function(c){return"'"+c.ID+"'";}).join(',');h+='<button class="btn btn-sm" style="background:'+color+';color:#fff" onclick="sendWABulk(['+ids+'])">Send All ('+items.length+')</button>';}h+='</div>';items.forEach(function(c){var dl=daysLeft(c.Deadline),dc=dl.cls==='overdue'?'#ef4444':dl.cls==='due-soon'?'#f59e0b':'#3b82f6',bg=dl.cls==='overdue'?'#fef2f2':dl.cls==='due-soon'?'#fffbeb':'#eff6ff';h+='<div class="reminder-row '+(dl.cls||'')+'"><div class="reminder-info"><div class="reminder-name">'+c.Name+'</div><div class="reminder-client">'+c.ClientName+'</div></div><div class="reminder-meta"><span class="reminder-days" style="color:'+dc+';background:'+bg+'">'+dl.label+'</span><span class="reminder-date">'+c.Deadline+'</span></div><button class="wa-btn" onclick="sendWAReminder(\''+c.ID+'\')">Send</button></div>';});if(!items.length)h+='<p style="color:#9ca3af;font-size:13px;padding:8px">None</p>';h+='</div>';}
remSection('Overdue','🔴','#ef4444',overdue);
remSection('Due This Week','🟡','#f59e0b',dueWeek);
remSection('Due This Month','🟢','#3b82f6',dueMon);
h+='<div class="card"><div class="card-title">Client-wise Bulk Summary</div><p style="font-size:13px;color:#6b7280;margin-bottom:16px">Send one WhatsApp per client with all pending items</p>';cls.forEach(function(cl){var pn=cs.filter(function(c){return c.ClientID===cl.ID&&c.Status!=='Filed'&&c.Status!=='Acknowledged';}).length;if(pn>0)h+='<div style="display:flex;align-items:center;justify-content:space-between;padding:10px 14px;border-radius:10px;border:1px solid #e5e7eb;margin-bottom:8px"><div><span style="font-weight:700">'+cl.LegalName+'</span><span style="font-size:12px;color:#6b7280;margin-left:12px">'+pn+' pending</span></div>'+(cl.Phone?'<button class="wa-btn" onclick="sendWASummary(\''+cl.ID+'\')">Send Summary</button>':'<span style="font-size:11px;color:#9ca3af">No phone</span>')+'</div>';});h+='</div>';el.innerHTML=h;}

// SETTINGS
function renderSettings(el){var fn=_s.get('firmName')||'';var staff=getStaff();el.innerHTML='<div class="page-header"><div><h1>Settings</h1></div></div><div class="settings-section"><h3>Google Apps Script</h3><div class="form-group"><label class="form-label">Web App URL</label><input class="form-input" id="set_url" value="'+(CONFIG.GAS_URL||'')+'" placeholder="https://script.google.com/macros/s/.../exec"><div class="form-hint">Deploy as Web App, paste URL here</div></div><button class="btn btn-primary btn-sm" onclick="saveGas()">Save & Test</button><div id="connTest" style="margin-top:12px"></div></div><div class="settings-section"><h3>Firm Details</h3><div class="form-group"><label class="form-label">Firm Name</label><input class="form-input" id="set_firm" value="'+fn+'" placeholder="e.g., Sharma & Associates"><div class="form-hint">Appears in WhatsApp messages, PDF reports, client portal</div></div><button class="btn btn-primary btn-sm" onclick="saveFirm()">Save</button></div><div class="settings-section"><h3>Staff Members ('+staff.length+')</h3><p style="font-size:13px;color:#6b7280;margin-bottom:12px">'+staff.map(function(s){return s.name+' ('+s.role+')';}).join(', ')+'</p><button class="btn btn-secondary btn-sm" onclick="navigateTo(\'team\')">Manage Team</button></div><div class="settings-section"><h3>Data Management</h3><p style="font-size:13px;color:#6b7280;margin-bottom:12px">Running locally in your browser.</p><div style="display:flex;gap:10px;flex-wrap:wrap"><button class="btn btn-secondary btn-sm" onclick="resetDemo()">Reset Demo Data</button><button class="btn btn-secondary btn-sm" onclick="exportData()">Export Data (JSON)</button><button class="btn btn-danger btn-sm" onclick="clearAll()">Clear All Data</button></div></div><div class="settings-section"><h3>About</h3><p style="font-size:13px;color:#6b7280;line-height:1.8">ComplianceDesk v'+CONFIG.VERSION+'<br>Features: WhatsApp Reminders • Auto Email • Doc Checklists • PDF Reports • Team Mgmt • Billing • Client Portal<br>Stack: Static HTML/JS + Google Apps Script + Sheets<br>Cost: 100% Free</p></div>';}
function saveGas(){var u=document.getElementById('set_url').value.trim();CONFIG.GAS_URL=u;updateConnectionStatus();document.getElementById('connTest').innerHTML=u?'<div class="info-box success"><div class="ib-text">URL saved.</div></div>':'<div class="info-box warning"><div class="ib-text">Cleared. Demo mode.</div></div>';}
function saveFirm(){var fn=document.getElementById('set_firm').value.trim();_s.set('firmName',fn);showToast('Firm name saved','success');}
function resetDemo(){if(!confirm('Reset demo data?'))return;Object.keys(localStorage).filter(function(k){return k.startsWith('cd_');}).forEach(function(k){localStorage.removeItem(k);});showToast('Reset','success');setTimeout(function(){navigateTo('dashboard');},500);}
function exportData(){var data={clients:getClients(),compliances:getComps(),communications:getComms(),invoices:getInvoices(),staff:getStaff(),firmName:_s.get('firmName')||''};var blob=new Blob([JSON.stringify(data,null,2)],{type:'application/json'});var a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='compliancedesk_backup_'+new Date().toISOString().split('T')[0]+'.json';a.click();showToast('Data exported','success');}
function clearAll(){if(!confirm('Clear ALL data?'))return;Object.keys(localStorage).filter(function(k){return k.startsWith('cd_');}).forEach(function(k){localStorage.removeItem(k);});showToast('Cleared','info');navigateTo('dashboard');}

// ============================================================
// DOCUMENT CHECKLISTS (Phase 3)
// ============================================================
var DOC_CHECKLISTS={
  'GSTR-1':['Sales invoices','Credit/debit notes','HSN summary','Export invoices','Advances received'],
  'GSTR-3B':['Output tax summary','Input tax credit details','ITC reversal details','Interest/late fee calculation','Bank statement for tax payment'],
  'TDS Return (24Q)':['Salary register','Form 16 draft','PAN of employees','TDS challans','Investment declarations'],
  'TDS Return':['TDS payment challans','Deductee PAN details','Section-wise TDS summary','Lower deduction certificates','Bank statements'],
  'ROC MGT-7':['Board resolution','Share capital details','Shareholder list','Transfer details','Minutes of AGM/EGM'],
  'ROC AOC-4':['Audited financial statements','Board report','Auditor report','Director responsibility statement','CSR report (if applicable)'],
  'LLP Form 11':['Partner details','Contribution details','Body corporate as partner details','Changes in partners'],
  'LLP Form 8':['Statement of accounts','Solvency statement','Signed by designated partners'],
  'Board Meeting':['Agenda items','Previous meeting minutes','Director attendance','Resolutions passed','Financial review documents'],
  'DIR-3 KYC':['Director PAN','Aadhaar card','Passport (if applicable)','Mobile & email verification','Residential proof'],
  'Income Tax Return':['Form 16/16A','Bank statements (all accounts)','Investment proofs (80C, 80D etc.)','Capital gains details','Rental income details','Foreign income/assets details','TDS certificates','Advance tax challans']
};

function getChecklist(compName){
  var cl=DOC_CHECKLISTS[compName];
  if(cl)return cl;
  // Partial match
  var keys=Object.keys(DOC_CHECKLISTS);
  for(var i=0;i<keys.length;i++){if(compName.indexOf(keys[i])>=0)return DOC_CHECKLISTS[keys[i]];}
  return['Document 1','Document 2','Document 3'];
}

function getCheckState(compId){return _s.get('chk_'+compId)||{};}
function setCheckState(compId,state){_s.set('chk_'+compId,state);}

function toggleDoc(compId,idx){
  var st=getCheckState(compId);
  st[idx]=!st[idx];
  setCheckState(compId,st);
  // Update UI
  var el=document.getElementById('dchk_'+compId+'_'+idx);
  if(el){el.className=st[idx]?'doc-item checked':'doc-item';el.querySelector('.doc-check').textContent=st[idx]?'✅':'⬜';}
  // Update counter
  var docs=getChecklist(window._chkCompName||'');
  var done=0;docs.forEach(function(_,i){if(st[i])done++;});
  var ctr=document.getElementById('dchk_count_'+compId);
  if(ctr)ctr.textContent=done+'/'+docs.length+' received';
  var pct=docs.length?Math.round(done/docs.length*100):0;
  var bar=document.getElementById('dchk_bar_'+compId);
  if(bar)bar.style.width=pct+'%';
}

function renderDocChecklist(compId,compName){
  window._chkCompName=compName;
  var docs=getChecklist(compName),st=getCheckState(compId);
  var done=0;docs.forEach(function(_,i){if(st[i])done++;});
  var pct=docs.length?Math.round(done/docs.length*100):0;
  var h='<div style="margin-top:16px;padding:16px;background:#f9fafb;border-radius:10px;border:1px solid #e5e7eb">';
  h+='<div style="display:flex;justify-content:space-between;align-items:center;margin-bottom:12px"><span style="font-size:13px;font-weight:700">📄 Document Checklist</span><span id="dchk_count_'+compId+'" style="font-size:12px;color:#6b7280">'+done+'/'+docs.length+' received</span></div>';
  h+='<div class="progress-bar" style="margin-bottom:12px"><div id="dchk_bar_'+compId+'" class="progress-fill" style="width:'+pct+'%;background:'+(pct===100?'#10b981':pct>=50?'#f59e0b':'#ef4444')+'"></div></div>';
  docs.forEach(function(doc,i){
    var checked=!!st[i];
    h+='<div id="dchk_'+compId+'_'+i+'" class="doc-item'+(checked?' checked':'')+'" onclick="toggleDoc(\''+compId+'\','+i+')" style="display:flex;align-items:center;gap:10px;padding:8px 12px;border-radius:8px;cursor:pointer;margin-bottom:4px;border:1px solid '+(checked?'#bbf7d0':'#e5e7eb')+';background:'+(checked?'#f0fdf4':'#fff')+';transition:all .15s">';
    h+='<span class="doc-check" style="font-size:16px">'+(checked?'✅':'⬜')+'</span>';
    h+='<span style="font-size:13px;'+(checked?'text-decoration:line-through;color:#9ca3af':'color:#374151')+'">'+doc+'</span></div>';
  });
  h+='</div>';
  return h;
}

// ============================================================
// PDF REPORT GENERATION (Phase 3)
// ============================================================
function generateClientReport(clientId){
  var cls=getClients(),cl=cls.find(function(x){return x.ID===clientId;});
  if(!cl){showToast('Client not found','error');return;}
  var cs=getComps({clientId:clientId});
  var td=new Date().toISOString().split('T')[0];
  var firm=_s.get('firmName')||'ComplianceDesk';
  var today=new Date().toLocaleDateString('en-IN',{day:'2-digit',month:'long',year:'numeric'});

  var filed=cs.filter(function(c){return c.Status==='Filed'||c.Status==='Acknowledged';}).length;
  var overdue=cs.filter(function(c){return c.Deadline<td&&c.Status!=='Filed'&&c.Status!=='Acknowledged';}).length;
  var pending=cs.filter(function(c){return c.Status!=='Filed'&&c.Status!=='Acknowledged';}).length;
  var pct=cs.length?Math.round(filed/cs.length*100):0;

  var html='<!DOCTYPE html><html><head><meta charset="UTF-8"><title>Compliance Report - '+cl.LegalName+'</title><style>*{margin:0;padding:0;box-sizing:border-box}body{font-family:Arial,sans-serif;font-size:12px;color:#333;padding:40px}h1{font-size:20px;color:#1a1a2e}h2{font-size:15px;color:#1a1a2e;margin:20px 0 10px;padding-bottom:6px;border-bottom:2px solid #e5e7eb}table{width:100%;border-collapse:collapse;margin:10px 0}th{background:#1a1a2e;color:#fff;padding:8px 10px;text-align:left;font-size:11px}td{padding:7px 10px;border-bottom:1px solid #e5e7eb;font-size:11px}.overdue{color:#ef4444;font-weight:700}.filed{color:#10b981}.header{display:flex;justify-content:space-between;align-items:flex-start;margin-bottom:24px;padding-bottom:16px;border-bottom:3px solid #1a1a2e}.stat{display:inline-block;padding:8px 16px;border-radius:6px;margin-right:8px;font-weight:700;font-size:13px}.badge{display:inline-block;padding:2px 8px;border-radius:10px;font-size:10px;font-weight:600}@media print{body{padding:20px}}</style></head><body>';
  html+='<div class="header"><div><h1>'+firm+'</h1><p style="color:#6b7280;margin-top:4px">Compliance Status Report</p></div><div style="text-align:right"><p style="font-weight:700;font-size:14px">'+cl.LegalName+'</p><p style="color:#6b7280">'+cl.ClientType+' | PAN: '+cl.PAN+'</p>'+(cl.GSTIN?'<p style="color:#6b7280">GSTIN: '+cl.GSTIN+'</p>':'')+'<p style="color:#6b7280">Generated: '+today+'</p></div></div>';

  html+='<div style="display:flex;gap:12px;margin-bottom:20px"><span class="stat" style="background:#eff6ff;color:#3b82f6">Total: '+cs.length+'</span><span class="stat" style="background:#ecfdf5;color:#10b981">Filed: '+filed+'</span><span class="stat" style="background:#fef2f2;color:#ef4444">Overdue: '+overdue+'</span><span class="stat" style="background:#fffbeb;color:#f59e0b">Pending: '+pending+'</span><span class="stat" style="background:#f5f3ff;color:#8b5cf6">Completion: '+pct+'%</span></div>';

  if(overdue>0){
    html+='<h2 style="color:#ef4444">Overdue Items</h2><table><tr><th>Compliance</th><th>Category</th><th>Deadline</th><th>Days Overdue</th><th>Status</th></tr>';
    cs.filter(function(c){return c.Deadline<td&&c.Status!=='Filed'&&c.Status!=='Acknowledged';}).sort(function(a,b){return a.Deadline.localeCompare(b.Deadline);}).forEach(function(c){var dl=daysLeft(c.Deadline);html+='<tr><td><strong>'+c.Name+'</strong></td><td>'+c.Category+'</td><td class="overdue">'+c.Deadline+'</td><td class="overdue">'+Math.abs(dl.days)+' days</td><td>'+c.Status+'</td></tr>';});
    html+='</table>';
  }

  html+='<h2>All Compliances</h2><table><tr><th>#</th><th>Compliance</th><th>Category</th><th>Period</th><th>Deadline</th><th>Status</th><th>Assigned</th></tr>';
  cs.sort(function(a,b){return(a.Deadline||'').localeCompare(b.Deadline||'');}).forEach(function(c,i){
    var isFiled=c.Status==='Filed'||c.Status==='Acknowledged';
    var isOv=c.Deadline<td&&!isFiled;
    html+='<tr><td>'+(i+1)+'</td><td><strong>'+c.Name+'</strong></td><td>'+c.Category+'</td><td>'+(c.Period||'')+'</td><td class="'+(isOv?'overdue':isFiled?'filed':'')+'">'+c.Deadline+'</td><td><span class="badge" style="background:'+(isFiled?'#ecfdf5;color:#059669':isOv?'#fef2f2;color:#ef4444':'#fffbeb;color:#92400e')+'">'+c.Status+'</span></td><td>'+(c.AssignedTo||'-')+'</td></tr>';
  });
  html+='</table>';
  html+='<div style="margin-top:30px;padding-top:16px;border-top:2px solid #e5e7eb;color:#9ca3af;font-size:10px"><p>This report was generated by ComplianceDesk on '+today+'. For queries contact '+firm+'.</p></div></body></html>';

  var win=window.open('','_blank');
  win.document.write(html);
  win.document.close();
  showToast('Report opened. Use Ctrl+P to save as PDF.','success');
}

// ============================================================
// TEAM / STAFF MANAGEMENT (Phase 4)
// ============================================================
function getStaff(){var s=_s.get('staff');if(!s){s=[{id:genId(),name:'Ravi',role:'Article Clerk',email:'',phone:'',active:true},{id:genId(),name:'Meena',role:'Senior Associate',email:'',phone:'',active:true},{id:genId(),name:'Suresh',role:'Associate',email:'',phone:'',active:true}];_s.set('staff',s);}return s;}
function renderTeam(el){
  var staff=getStaff(),cs=getComps(),td=new Date().toISOString().split('T')[0];
  var h='<div class="page-header"><div><h1>Team Management</h1><div class="subtitle">'+staff.length+' members</div></div><button class="btn btn-primary" onclick="showStaffForm()">+ Add Member</button></div>';
  // Staff cards with workload
  h+='<div style="display:grid;grid-template-columns:repeat(auto-fill,minmax(300px,1fr));gap:16px">';
  staff.filter(function(s){return s.active;}).forEach(function(s){
    var assigned=cs.filter(function(c){return c.AssignedTo===s.name;});
    var pending=assigned.filter(function(c){return c.Status!=='Filed'&&c.Status!=='Acknowledged';});
    var overdue=assigned.filter(function(c){return c.Deadline<td&&c.Status!=='Filed'&&c.Status!=='Acknowledged';});
    var filed=assigned.filter(function(c){return c.Status==='Filed'||c.Status==='Acknowledged';});
    var pct=assigned.length?Math.round(filed.length/assigned.length*100):0;
    h+='<div class="card" style="padding:20px"><div style="display:flex;justify-content:space-between;align-items:start;margin-bottom:14px"><div><div style="font-size:16px;font-weight:700">'+s.name+'</div><div style="font-size:12px;color:#6b7280">'+(s.role||'Staff')+'</div></div><div style="display:flex;gap:6px"><button class="wa-btn-sm" onclick="showStaffForm(\''+s.id+'\')" title="Edit" style="background:#3b82f615;font-size:13px">✏️</button></div></div>';
    h+='<div style="display:grid;grid-template-columns:1fr 1fr;gap:8px;margin-bottom:12px"><div style="padding:8px;border-radius:8px;background:#eff6ff;text-align:center"><div style="font-size:18px;font-weight:800;color:#3b82f6">'+assigned.length+'</div><div style="font-size:10px;color:#6b7280">Total</div></div><div style="padding:8px;border-radius:8px;background:#fef2f2;text-align:center"><div style="font-size:18px;font-weight:800;color:#ef4444">'+overdue.length+'</div><div style="font-size:10px;color:#6b7280">Overdue</div></div></div>';
    h+='<div style="display:flex;justify-content:space-between;margin-bottom:6px"><span style="font-size:11px;color:#6b7280">Completion</span><span style="font-size:11px;font-weight:700">'+pct+'%</span></div><div class="progress-bar"><div class="progress-fill" style="width:'+pct+'%;background:'+(pct>=70?'#10b981':pct>=40?'#f59e0b':'#ef4444')+'"></div></div>';
    // Recent pending items
    if(pending.length>0){h+='<div style="margin-top:12px;font-size:11px;color:#6b7280;font-weight:600">Pending ('+pending.length+')</div>';pending.sort(function(a,b){return(a.Deadline||'').localeCompare(b.Deadline||'');}).slice(0,4).forEach(function(c){var dl=daysLeft(c.Deadline),dc=dl.cls==='overdue'?'#ef4444':dl.cls==='due-soon'?'#f59e0b':'#6b7280';h+='<div style="display:flex;justify-content:space-between;padding:4px 0;font-size:11px"><span>'+c.Name+' <span style="color:#9ca3af">'+c.ClientName+'</span></span><span style="color:'+dc+';font-weight:600">'+dl.label+'</span></div>';});if(pending.length>4)h+='<div style="font-size:10px;color:#9ca3af;margin-top:4px">+'+(pending.length-4)+' more</div>';}
    h+='</div>';
  });
  h+='</div>';
  // Workload comparison chart
  h+='<div class="card" style="margin-top:20px"><div class="card-title">Workload Distribution</div>';
  var maxLoad=0;staff.filter(function(s){return s.active;}).forEach(function(s){var n=cs.filter(function(c){return c.AssignedTo===s.name&&c.Status!=='Filed'&&c.Status!=='Acknowledged';}).length;if(n>maxLoad)maxLoad=n;});
  staff.filter(function(s){return s.active;}).forEach(function(s){
    var pend=cs.filter(function(c){return c.AssignedTo===s.name&&c.Status!=='Filed'&&c.Status!=='Acknowledged';}).length;
    var ov=cs.filter(function(c){return c.AssignedTo===s.name&&c.Deadline<td&&c.Status!=='Filed'&&c.Status!=='Acknowledged';}).length;
    var w=maxLoad?Math.round(pend/maxLoad*100):0;
    h+='<div style="display:flex;align-items:center;gap:12px;margin-bottom:10px"><span style="width:80px;font-size:13px;font-weight:600">'+s.name+'</span><div style="flex:1"><div class="progress-bar" style="height:24px;border-radius:6px"><div class="progress-fill" style="width:'+w+'%;background:'+(ov>0?'linear-gradient(90deg,#ef4444,#f59e0b)':'#3b82f6')+';border-radius:6px;display:flex;align-items:center;padding-left:8px"><span style="font-size:11px;color:#fff;font-weight:700">'+pend+' pending'+(ov>0?' ('+ov+' overdue)':'')+'</span></div></div></div></div>';
  });
  h+='</div>';
  el.innerHTML=h;
}
function showStaffForm(sid){var staff=getStaff(),s=sid?staff.find(function(x){return x.id===sid;}):null;openModal(s?'Edit Member':'Add Team Member','<div class="form-group"><label class="form-label">Name <span class="required">*</span></label><input class="form-input" id="sf_name" value="'+(s?s.name:'')+'"></div><div class="form-group"><label class="form-label">Role</label><input class="form-input" id="sf_role" value="'+(s?s.role||'':'')+'" placeholder="e.g., Article Clerk, Senior Associate"></div><div class="form-row"><div class="form-group"><label class="form-label">Email</label><input class="form-input" id="sf_email" value="'+(s?s.email||'':'')+'"></div><div class="form-group"><label class="form-label">Phone</label><input class="form-input" id="sf_phone" value="'+(s?s.phone||'':'')+'" maxlength="10"></div></div><div class="modal-footer">'+(s?'<button class="btn btn-danger btn-sm" onclick="removeStaff(\''+sid+'\')">Remove</button>':'')+'<button class="btn btn-secondary" onclick="closeModal()">Cancel</button><button class="btn btn-primary" onclick="submitStaff(\''+(sid||'')+'\')">'+(s?'Update':'Add')+'</button></div>');}
function submitStaff(sid){var name=document.getElementById('sf_name').value.trim();if(!name){showToast('Name required','error');return;}var staff=getStaff();if(sid){var idx=staff.findIndex(function(s){return s.id===sid;});if(idx>=0){var oldName=staff[idx].name;staff[idx].name=name;staff[idx].role=document.getElementById('sf_role').value.trim();staff[idx].email=document.getElementById('sf_email').value.trim();staff[idx].phone=document.getElementById('sf_phone').value.trim();_s.set('staff',staff);if(oldName!==name){var cs=_s.get('compliances')||[];cs.forEach(function(c){if(c.AssignedTo===oldName)c.AssignedTo=name;});_s.set('compliances',cs);}}}else{staff.push({id:genId(),name:name,role:document.getElementById('sf_role').value.trim(),email:document.getElementById('sf_email').value.trim(),phone:document.getElementById('sf_phone').value.trim(),active:true});_s.set('staff',staff);CONFIG.STAFF.push(name);}closeModal();showToast(sid?'Updated':'Added','success');renderTeam(document.getElementById('pageContent'));}
function removeStaff(sid){if(!confirm('Remove this team member?'))return;var staff=getStaff();staff=staff.filter(function(s){return s.id!==sid;});_s.set('staff',staff);closeModal();showToast('Removed','success');renderTeam(document.getElementById('pageContent'));}

// ============================================================
// BILLING / INVOICE TRACKER (Phase 4)
// ============================================================
function getInvoices(){return _s.get('invoices')||[];}
function renderBilling(el){
  var invs=getInvoices(),cls=getClients();
  var total=0,paid=0,unpaid=0,overdue=0,td=new Date().toISOString().split('T')[0];
  invs.forEach(function(inv){total+=inv.amount;if(inv.status==='Paid')paid+=inv.amount;else{unpaid+=inv.amount;if(inv.dueDate<td)overdue+=inv.amount;}});
  var h='<div class="page-header"><div><h1>Billing & Invoices</h1><div class="subtitle">'+invs.length+' invoices</div></div><button class="btn btn-primary" onclick="showInvoiceForm()">+ New Invoice</button></div>';
  h+='<div class="stat-grid" style="grid-template-columns:repeat(4,1fr)"><div class="stat-card" style="background:#eff6ff"><div class="stat-value" style="color:#3b82f6;font-size:20px">₹'+formatNum(total)+'</div><div class="stat-label" style="color:#3b82f6">Total Billed</div></div><div class="stat-card" style="background:#ecfdf5"><div class="stat-value" style="color:#10b981;font-size:20px">₹'+formatNum(paid)+'</div><div class="stat-label" style="color:#10b981">Received</div></div><div class="stat-card" style="background:#fffbeb"><div class="stat-value" style="color:#f59e0b;font-size:20px">₹'+formatNum(unpaid)+'</div><div class="stat-label" style="color:#f59e0b">Outstanding</div></div><div class="stat-card" style="background:#fef2f2"><div class="stat-value" style="color:#ef4444;font-size:20px">₹'+formatNum(overdue)+'</div><div class="stat-label" style="color:#ef4444">Overdue</div></div></div>';
  // Invoices table
  h+='<div class="card"><div class="table-container" style="border:none"><table class="data-table"><thead><tr><th>Invoice #</th><th>Client</th><th>Description</th><th>Amount</th><th>Due Date</th><th>Status</th><th>Actions</th></tr></thead><tbody>';
  invs.sort(function(a,b){return(b.createdAt||'').localeCompare(a.createdAt||'');}).forEach(function(inv){
    var isOv=inv.status!=='Paid'&&inv.dueDate<td;
    h+='<tr style="background:'+(isOv?'#fef2f2':'transparent')+'"><td style="font-weight:700">'+inv.number+'</td><td>'+inv.clientName+'</td><td style="font-size:12px;color:#6b7280">'+inv.description+'</td><td style="font-weight:700">₹'+formatNum(inv.amount)+'</td><td style="color:'+(isOv?'#ef4444':'#374151')+'">'+inv.dueDate+'</td><td><span class="badge-sm" style="background:'+(inv.status==='Paid'?'#ecfdf5;color:#059669':isOv?'#fef2f2;color:#ef4444':'#fffbeb;color:#92400e')+'">'+inv.status+'</span></td><td style="white-space:nowrap">'+(inv.status!=='Paid'?'<button class="btn btn-sm" style="font-size:11px;padding:4px 10px" onclick="markPaid(\''+inv.id+'\')">Mark Paid</button> ':'')+'<button class="wa-btn-sm" onclick="sendInvoiceWA(\''+inv.id+'\')" title="Send via WhatsApp">💬</button></td></tr>';
  });
  h+='</tbody></table></div></div>';
  if(!invs.length)h+='<p style="text-align:center;padding:40px;color:#9ca3af">No invoices yet. Create your first invoice above.</p>';
  // Client-wise summary
  if(invs.length>0){
    h+='<div class="card" style="margin-top:16px"><div class="card-title">Client-wise Billing Summary</div>';
    var clMap={};invs.forEach(function(inv){if(!clMap[inv.clientId])clMap[inv.clientId]={name:inv.clientName,total:0,paid:0};clMap[inv.clientId].total+=inv.amount;if(inv.status==='Paid')clMap[inv.clientId].paid+=inv.amount;});
    Object.keys(clMap).forEach(function(cid){var c=clMap[cid],pct=c.total?Math.round(c.paid/c.total*100):0;h+='<div style="display:flex;align-items:center;gap:12px;margin-bottom:10px;padding:10px 14px;border-radius:10px;border:1px solid #e5e7eb"><span style="width:180px;font-weight:600;font-size:13px">'+c.name+'</span><div style="flex:1"><div class="progress-bar"><div class="progress-fill" style="width:'+pct+'%;background:#10b981"></div></div></div><span style="font-size:12px;font-weight:700;width:120px;text-align:right">₹'+formatNum(c.paid)+' / ₹'+formatNum(c.total)+'</span></div>';});
    h+='</div>';
  }
  el.innerHTML=h;
}
function formatNum(n){return n.toLocaleString('en-IN');}
function showInvoiceForm(){var cls=getClients(),co=cls.map(function(c){return'<option value="'+c.ID+'" data-name="'+c.LegalName+'">'+c.LegalName+'</option>';}).join('');var nextNum='INV-'+String(getInvoices().length+1).padStart(4,'0');openModal('New Invoice','<div class="form-row"><div class="form-group"><label class="form-label">Invoice # <span class="required">*</span></label><input class="form-input" id="inv_num" value="'+nextNum+'"></div><div class="form-group"><label class="form-label">Client <span class="required">*</span></label><select class="form-input" id="inv_cl"><option value="">Select</option>'+co+'</select></div></div><div class="form-group"><label class="form-label">Description</label><input class="form-input" id="inv_desc" placeholder="e.g., GST Filing Q1 2026, Annual Compliance Package"></div><div class="form-row"><div class="form-group"><label class="form-label">Amount (₹) <span class="required">*</span></label><input class="form-input" type="number" id="inv_amt" placeholder="0"></div><div class="form-group"><label class="form-label">Due Date <span class="required">*</span></label><input class="form-input" type="date" id="inv_due"></div></div><div class="form-group"><label class="form-label">Notes</label><textarea class="form-input" id="inv_notes" placeholder="Payment terms, bank details etc."></textarea></div><div class="modal-footer"><button class="btn btn-secondary" onclick="closeModal()">Cancel</button><button class="btn btn-primary" onclick="submitInvoice()">Create Invoice</button></div>');}
function submitInvoice(){var sel=document.getElementById('inv_cl'),amt=parseFloat(document.getElementById('inv_amt').value),due=document.getElementById('inv_due').value;if(!sel.value||!amt||!due){showToast('Fill all required fields','error');return;}var invs=getInvoices();invs.push({id:genId(),number:document.getElementById('inv_num').value.trim(),clientId:sel.value,clientName:sel.options[sel.selectedIndex].dataset.name,description:document.getElementById('inv_desc').value.trim(),amount:amt,dueDate:due,status:'Unpaid',notes:document.getElementById('inv_notes').value.trim(),createdAt:new Date().toISOString()});_s.set('invoices',invs);closeModal();showToast('Invoice created','success');renderBilling(document.getElementById('pageContent'));}
function markPaid(invId){var invs=getInvoices(),inv=invs.find(function(i){return i.id===invId;});if(inv){inv.status='Paid';inv.paidAt=new Date().toISOString();_s.set('invoices',invs);showToast('Marked as paid','success');renderBilling(document.getElementById('pageContent'));}}
function sendInvoiceWA(invId){var invs=getInvoices(),inv=invs.find(function(i){return i.id===invId;});if(!inv)return;var cls=getClients(),cl=cls.find(function(c){return c.ID===inv.clientId;});if(!cl||!cl.Phone){showToast('No phone number','error');return;}var firm=_s.get('firmName')||'';var msg='Dear '+(cl.ContactName||cl.LegalName)+',\n\nInvoice *'+inv.number+'* has been raised:\n\n';msg+='📄 *Description:* '+inv.description+'\n💰 *Amount:* ₹'+formatNum(inv.amount)+'\n📅 *Due Date:* '+inv.dueDate+'\n\n';msg+='Please arrange payment at your earliest convenience.';if(inv.notes)msg+='\n\n_'+inv.notes+'_';if(firm)msg+='\n\nRegards,\n'+firm;openWhatsApp(cl.Phone,msg);apiLogComm({clientId:cl.ID,clientName:cl.LegalName,type:'Reminder',channel:'WhatsApp',message:'Invoice '+inv.number+' sent: ₹'+formatNum(inv.amount)});}

// ============================================================
// CLIENT PORTAL (Phase 4) - Shareable link per client
// ============================================================
function renderPortal(el){
  var cls=getClients(),cs=getComps(),td=new Date().toISOString().split('T')[0],firm=_s.get('firmName')||'ComplianceDesk';
  var h='<div class="page-header"><div><h1>Client Portal</h1><div class="subtitle">Generate shareable status pages for clients</div></div></div>';
  h+='<div class="card" style="margin-bottom:20px;background:#eff6ff;border:1px solid #bfdbfe"><div style="display:flex;align-items:start;gap:12px"><span style="font-size:24px">ℹ️</span><div><div style="font-weight:700;color:#1e40af;margin-bottom:4px">How Client Portal Works</div><div style="font-size:13px;color:#3b82f6">Click "Generate Link" for any client. A standalone HTML page opens in a new tab showing their compliance status. They can bookmark it or you can share it via WhatsApp/Email. The page works offline once opened — no login required.</div></div></div></div>';
  cls.forEach(function(cl){
    var cc=cs.filter(function(c){return c.ClientID===cl.ID;}),pend=cc.filter(function(c){return c.Status!=='Filed'&&c.Status!=='Acknowledged';}),ov=cc.filter(function(c){return c.Deadline<td&&c.Status!=='Filed'&&c.Status!=='Acknowledged';});
    var pct=cc.length?Math.round((cc.length-pend.length)/cc.length*100):0;
    h+='<div class="card" style="margin-bottom:12px"><div style="display:flex;align-items:center;justify-content:space-between"><div><div style="font-size:15px;font-weight:700">'+cl.LegalName+'</div><div style="font-size:12px;color:#6b7280;margin-top:2px">'+cl.ClientType+' | '+pend.length+' pending'+(ov.length>0?' | <span style="color:#ef4444;font-weight:600">'+ov.length+' overdue</span>':'')+'</div></div><div style="display:flex;gap:8px;align-items:center"><span style="font-size:13px;font-weight:700;color:'+(pct>=70?'#10b981':pct>=40?'#f59e0b':'#ef4444')+'">'+pct+'%</span><button class="btn btn-primary btn-sm" onclick="generatePortalPage(\''+cl.ID+'\')">Generate Link</button>'+(cl.Phone?'<button class="wa-btn-sm" onclick="sharePortalWA(\''+cl.ID+'\')" title="Share via WhatsApp">📱</button>':'')+'</div></div></div>';
  });
  el.innerHTML=h;
}
function generatePortalPage(clientId){
  var cls=getClients(),cl=cls.find(function(c){return c.ID===clientId;});if(!cl)return;
  var cs=getComps({clientId:clientId}),td=new Date().toISOString().split('T')[0];
  var firm=_s.get('firmName')||'ComplianceDesk';
  var today=new Date().toLocaleDateString('en-IN',{day:'2-digit',month:'long',year:'numeric'});
  var filed=cs.filter(function(c){return c.Status==='Filed'||c.Status==='Acknowledged';}).length;
  var overdue=cs.filter(function(c){return c.Deadline<td&&c.Status!=='Filed'&&c.Status!=='Acknowledged';}).length;
  var pending=cs.filter(function(c){return c.Status!=='Filed'&&c.Status!=='Acknowledged';}).length;
  var pct=cs.length?Math.round(filed/cs.length*100):0;

  var html='<!DOCTYPE html><html><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>'+cl.LegalName+' - Compliance Status</title><style>*{margin:0;padding:0;box-sizing:border-box}body{font-family:-apple-system,BlinkMacSystemFont,sans-serif;background:#f8fafc;color:#374151}.hdr{background:linear-gradient(135deg,#1a1a2e,#16213e);color:#fff;padding:32px 24px}.hdr h1{font-size:22px;margin-bottom:4px}.hdr p{opacity:.7;font-size:13px}.stats{display:grid;grid-template-columns:repeat(auto-fit,minmax(140px,1fr));gap:12px;padding:20px;max-width:900px;margin:0 auto}.sc{background:#fff;border-radius:12px;padding:16px;text-align:center;box-shadow:0 1px 3px rgba(0,0,0,.08)}.sc .v{font-size:24px;font-weight:800}.sc .l{font-size:11px;color:#6b7280;margin-top:2px}.main{max-width:900px;margin:0 auto;padding:0 20px 40px}table{width:100%;border-collapse:collapse;margin-top:16px;background:#fff;border-radius:12px;overflow:hidden;box-shadow:0 1px 3px rgba(0,0,0,.08)}th{background:#f9fafb;padding:10px 12px;font-size:11px;font-weight:700;color:#6b7280;text-align:left;text-transform:uppercase}td{padding:10px 12px;border-top:1px solid #f3f4f6;font-size:13px}.ov{color:#ef4444;font-weight:700}.fl{color:#10b981;font-weight:700}.badge{display:inline-block;padding:3px 10px;border-radius:10px;font-size:10px;font-weight:700}.prg{height:6px;background:#e5e7eb;border-radius:3px;overflow:hidden}.prg-f{height:100%;border-radius:3px}@media(max-width:600px){.stats{grid-template-columns:1fr 1fr}}</style></head><body>';
  html+='<div class="hdr"><h1>'+firm+'</h1><p>Compliance Status Report for <strong>'+cl.LegalName+'</strong></p><p style="margin-top:8px;opacity:.5;font-size:11px">Generated: '+today+'</p></div>';
  html+='<div class="stats"><div class="sc"><div class="v" style="color:#3b82f6">'+cs.length+'</div><div class="l">Total</div></div><div class="sc"><div class="v" style="color:#10b981">'+filed+'</div><div class="l">Filed</div></div><div class="sc"><div class="v" style="color:#ef4444">'+overdue+'</div><div class="l">Overdue</div></div><div class="sc"><div class="v" style="color:#8b5cf6">'+pct+'%</div><div class="l">Complete</div></div></div>';
  html+='<div class="main">';
  if(overdue>0){
    html+='<h3 style="color:#ef4444;margin:20px 0 8px;font-size:15px">⚠️ Overdue Items (Action Required)</h3><table>';
    html+='<tr><th>Compliance</th><th>Category</th><th>Deadline</th><th>Days Overdue</th><th>Documents Needed</th></tr>';
    cs.filter(function(c){return c.Deadline<td&&c.Status!=='Filed'&&c.Status!=='Acknowledged';}).sort(function(a,b){return a.Deadline.localeCompare(b.Deadline);}).forEach(function(c){
      var days=Math.ceil((new Date()-new Date(c.Deadline))/86400000);
      var docs=getChecklist(c.Name).join(', ');
      html+='<tr><td><strong>'+c.Name+'</strong></td><td>'+c.Category+'</td><td class="ov">'+c.Deadline+'</td><td class="ov">'+days+' days</td><td style="font-size:11px;color:#6b7280">'+docs+'</td></tr>';
    });
    html+='</table>';
  }
  html+='<h3 style="margin:24px 0 8px;font-size:15px">All Compliances</h3><table>';
  html+='<tr><th>#</th><th>Compliance</th><th>Category</th><th>Deadline</th><th>Status</th></tr>';
  cs.sort(function(a,b){return(a.Deadline||'').localeCompare(b.Deadline||'');}).forEach(function(c,i){
    var isFiled=c.Status==='Filed'||c.Status==='Acknowledged',isOv=c.Deadline<td&&!isFiled;
    var stCol=isFiled?'#ecfdf5;color:#059669':isOv?'#fef2f2;color:#ef4444':'#fffbeb;color:#92400e';
    html+='<tr><td>'+(i+1)+'</td><td><strong>'+c.Name+'</strong></td><td>'+c.Category+'</td><td class="'+(isOv?'ov':isFiled?'fl':'')+'">'+c.Deadline+'</td><td><span class="badge" style="background:'+stCol+'">'+c.Status+'</span></td></tr>';
  });
  html+='</table>';
  html+='<div style="margin-top:32px;padding-top:16px;border-top:1px solid #e5e7eb;color:#9ca3af;font-size:11px;text-align:center"><p>This report was generated by '+firm+' using ComplianceDesk on '+today+'.</p><p>For queries, please contact your CA/CS directly.</p></div></div></body></html>';

  var win=window.open('','_blank');
  win.document.write(html);
  win.document.close();
  showToast('Portal page opened. Client can bookmark this page.','success');
}
function sharePortalWA(clientId){var cls=getClients(),cl=cls.find(function(c){return c.ID===clientId;});if(!cl||!cl.Phone){showToast('No phone','error');return;}var firm=_s.get('firmName')||'';var msg='Dear '+(cl.ContactName||cl.LegalName)+',\n\nYour compliance status report is ready. Please check your email or contact us for the latest status of your filings.\n\nFor any document submissions, please reply to this message.';if(firm)msg+='\n\nRegards,\n'+firm;openWhatsApp(cl.Phone,msg);apiLogComm({clientId:cl.ID,clientName:cl.LegalName,type:'Update',channel:'WhatsApp',message:'Portal link shared'});}

// INIT
document.addEventListener('DOMContentLoaded',function(){updateConnectionStatus();navigateTo('dashboard');});
